RESUME=resume
CV=cv
COVERLETTER=coverletter

BUILD_FOLDER=build
OUTPUT_FOLDER=output
OUTPUT_FORMAT=pdf

LATEXMK=latexmk
COMPILER=-xelatex
BUILD_DIRECTORY=-output-directory=$(BUILD_FOLDER)
INTERACTION=-interaction=nonstopmode
USE_MAKE=-use-make
QUIET=-quiet

LATEXMK_OPTIONS=$(BUILD_DIRECTORY) -$(OUTPUT_FORMAT) $(COMPILER) $(INTERACTION) $(USE_MAKE) $(QUIET)

.PHONY: all clean cleanall $(RESUME) $(CV) $(COVERLETTER)

all: $(RESUME) $(CV) $(COVERLETTER)

$(RESUME): $(RESUME).tex
	mkdir -p $(BUILD_FOLDER) $(OUTPUT_FOLDER)
	$(LATEXMK) $(LATEXMK_OPTIONS) $<
	mv $(BUILD_FOLDER)/$@.$(OUTPUT_FORMAT) $(OUTPUT_FOLDER)/$@.$(OUTPUT_FORMAT)

$(CV): $(CV).tex
	mkdir -p $(BUILD_FOLDER) $(OUTPUT_FOLDER)
	$(LATEXMK) $(LATEXMK_OPTIONS) $<
	mv $(BUILD_FOLDER)/$@.$(OUTPUT_FORMAT) $(OUTPUT_FOLDER)/$@.$(OUTPUT_FORMAT)

$(COVERLETTER): $(COVERLETTER).tex
	mkdir -p $(BUILD_FOLDER) $(OUTPUT_FOLDER)
	$(LATEXMK) $(LATEXMK_OPTIONS) $<
	mv $(BUILD_FOLDER)/$@.$(OUTPUT_FORMAT) $(OUTPUT_FOLDER)/$@.$(OUTPUT_FORMAT)

clean:
	rm -rf $(BUILD_FOLDER)

cleanall:
	rm -rf $(BUILD_FOLDER)
	rm -rf $(OUTPUT_FOLDER)
